[build]
  command = "pnpm --filter @hotelcheckin/database exec prisma generate --schema=prisma/schema.prisma && pnpm turbo build --filter=@hotelcheckin/web..."
  publish = "apps/web/.next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://hotelcheckin-api.fly.dev"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
